//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public bool Viewed { get; set; }
        public NotificationType NotificationType { get; set; }
        public string AspNetUserId { get; set; }
        public string AspNetUserId1 { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser SourceUser { get; set; }
    }
}
